### ISSUE TITLE
Need to specify baudrate to specify data

### ISSUE THREAD

**Issue by JamesNewton** [Hack-a-Day/2022-Supercon6-Badge-Tools#2]
Those instructions didn't work for us on Ubuntu 18.04 until we included the baud rate on the `stty -F /dev/ttyUSB0 raw 9600` line. And you set / check the baud on the badge in dir mode with alt and then look at / change the Operand X values. 0011 is 9600 (default). . Then enter `cat /dev/ttyUSB0 > out.hex` and press the Save button (still in Dir)

**Comment by MS3FGX** [comment]
Talked to Mike Szczys, and he confirmed that back when he originally wrote the README for the assembler, the baud rate was supposed to be included in the stty command. I'll make sure it gets added, thanks for pointing it out.

Obviously doesn't seem to be required on _all_ setups, since none of us here have had to do it while working with the badge, but there are so many different hardware/software permutations that it's impossible to say anything for sure.

**Comment by MS3FGX** [comment]
This has been addressed as of latest commit.
